CREATE TABLE users(
    id BIGSERIAL PRIMARY KEY
    , username VARCHAR(50) NOT NULL UNIQUE
    , email VARCHAR(255) NOT NULL UNIQUE
    , password_hash VARCHAR(255) NOT NULL
    , role VARCHAR(50) NOT NULL DEFAULT 'USER'
    , created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    , updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);