CREATE TABLE refresh_tokens(
    id BIGSERIAL PRIMARY KEY
    , user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE
    , token VARCHAR(255) NOT NULL UNIQUE
    , expiry_date TIMESTAMP WITH TIME ZONE NOT NULL
);

